language: objective-c
osx_image: xcode10.2
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - PROJECT=CallbackURLKit.xcodeproj
    - IOS_FRAMEWORK_SCHEME="CallbackURLKit"
    - MACOS_FRAMEWORK_SCHEME="CallbackURLKitOSX"
    - IOS_SDK=iphonesimulator12.2
    - MACOS_SDK=macosx10.14
  matrix:
    - DESTINATION="OS=12.2,name=iPhone 8" SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK" RUN_TESTS="NO"
    - DESTINATION="arch=x86_64" SCHEME="$MACOS_FRAMEWORK_SCHEME" SDK="$MACOS_SDK" RUN_TESTS="NO"
before_install:
  - gem install xcpretty --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    else
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi
after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
