disabled_rules:
  - identifier_name
  - line_length
  - trailing_whitespace
  - force_cast
  - file_length
  - function_body_length
  - nesting
  - notification_center_detachment
  - unused_setter_value
  - cyclomatic_complexity
  - type_body_length
  - force_try
  - implicit_getter
  - large_tuple

excluded:
  - Pods

analyzer_rules:
  - unused_import
  