import AppKit

extension NSPasteboard {
    var typesAreSensitive: Bool {
        guard let t = types else {
            return false
        }

        let sensitiveTypes = [
            "org.nspasteboard.TransientType",
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.AutoGeneratedType"
        ]
        return t.contains { sensitiveTypes.contains($0.rawValue) }
    }
}
